Error: identical code works for (_: Unit) => ... spores, but not for Nullary spores
Minimal example in NullaryUnitSporeComparison test

(cherry picked from commit e2c0a8e554d799d5d0ef2caaf23aa42a24aca7ba)